payment = input("What is the annual annuity payment? ")
rate = input("What is the rate? ")
time = input("What is the time period? ")
number = input("What is the number of times it will be payed annually? ")
PMT = float(payment)
R = float(rate)
t = float(time)
n = float(number)
amount  = (PMT * ((( 1.0 + ( R / n )) ** (n*t)) - 1) / (R / n))
print("The annuity plan amount is: $" +  str(amount))