vdef reciept():
    window2 = tk.Toplevel(root)
    window2.title("Price Box")
    window2.geometry("700x700")

    name = name_entry.get()
    rices = rices_entry.get()
    rquantity = int(rquantity_entry.get())
    si = si_entry.get()
    si_quantity = int(si_quantity_entry.get())
    so = so_entry.get()
    so_quantity = int(so_quantity_entry.get())
    pr = pr_entry.get()
    pr_quantity = int(pr_quantity_entry.get())
    be = be_entry.get()
    be_quantity = int(be_quantity_entry.get())


    label_1 = tk.Label(window2, text=f"Welcome {name}. Here is a reciept of your order")
    label_1.pack()
    label_2 = tk.Label(window2, text=f"Rice/Pasta order: {rices}")
    label_2.pack()
    label_3 = tk.Label(window2, text=f"Quantity of rice: {rquantity}")
    label_3.pack()
    label_4 = tk.Label(window2, text=f"Side dish order: {si}")
    label_4.pack()
    label_5 = tk.Label(window2, text=f"Side dish quantity: {si_quantity}")
    label_5.pack()
    label_6 = tk.Label(window2, text=f"Soup/Swallow order: {so}")
    label_6.pack()
    label_7 = tk.Label(window2, text=f"Soup/Swallow quantity: {so_quantity}")
    label_7.pack()
    label_8 = tk.Label(window2, text=f"Protien order: {pr}")
    label_8.pack()
    label_9 = tk.Label(window2, text=f"Protien quantity: {pr_quantity}")
    label_9.pack()
    label_10 = tk.Label(window2, text=f"Beverage order: {be}")
    label_10.pack()
    label_11 = tk.Label(window2, text=f"Beverage quantity: {be_quantity}")
    label_11.pack()
    label_12 = tk.Label(window2, text=f"Total Price: N{total_price}")
    label_12.pack()


order_button = tk.Button(root, text="ORDER", command=)
    order_button.pack()
    order_button.config(fg="Red", bg="Black")